### ISSUE TITLE
US7T2 - Have a list of locations (city or area vs coordinates)

### ISSUE THREAD

**Issue by pilarsantolaria** [ADS2018UB/twitterhappiness#30]

**Comment by eduribas92** [comment]
The list of cities can be regenerated by modifying and executing the file `location_data_load.py`:
`$ cd dataflow/`
`$ python location_data_load.py `

The list now includes: 
New York, Washington, Los Angeles, Chicago, Houston, Boston, Sydney, Ottawa, Toronto, Montreal
